class NPCData {
  static const Map<String, NPC> npcMap = {
    'elias_thorne': NPC(
      id: 'elias_thorne',
      name: 'Elias Thorne',
      role: 'The Historian',
      vibe: 'Scholarly, slightly unhinged',
      clueStyle: 'Historical riddles tied to real locations',
      voiceLine: 'The archive breathes. Consult it wisely.',
      avatarAsset: 'assets/npcs/elias.png',
      pathId: 'colonial_echoes',
      specialFeature: 'Unlocks historical hints based on completed paths',
    ),
    'maizy_gears': NPC(
      id: 'maizy_gears',
      name: 'Maizy Gears',
      role: 'The Engineer',
      vibe: 'Steampunk tech nerd',
      clueStyle: 'Schematics, sound puzzles, Morse code',
      voiceLine: 'Every gear has a story. Let’s tune it.',
      avatarAsset: 'assets/npcs/maizy.png',
      pathId: 'industrial_trail',
      specialFeature: 'Modifies clues if players earn gear fragments',
    ),
    'bishop_and_clover': NPC(
      id: 'bishop_and_clover',
      name: 'Bishop & Clover',
      role: 'The Rival Explorers',
      vibe: 'Suave vs skeptical; playful banter',
      clueStyle: 'Competing clues, branching paths',
      voiceLine: 'Trust one. Doubt both.',
      avatarAsset: 'assets/npcs/bishop_clover.png',
      pathId: 'victorian_secrets',
      specialFeature: 'Unlocks hidden mini-games when interacted with together',
    ),
    'madame_roux': NPC(
      id: 'madame_roux',
      name: 'Madame Roux',
      role: 'The Secret Spice Archivist',
      vibe: 'Cloaked, elegant, metaphorical',
      clueStyle: 'Olfactory riddles, recipe ciphers',
      voiceLine: 'The spice must be remembered.',
      avatarAsset: 'assets/npcs/roux.png',
      pathId: 'flavor_fugue',
      specialFeature: 'Unlocks Sensory Vault when rare spices are sourced',
    ),
    'the_curator': NPC(
      id: 'the_curator',
      name: 'The Curator',
      role: 'Keeper of the Capsule',
      vibe: 'Calm, cryptic, possibly otherworldly',
      clueStyle: 'Symbolic dreams, questions only',
      voiceLine: 'The capsule waits. Are you ready?',
      avatarAsset: 'assets/npcs/curator.png',
      pathId: 'capsule',
      specialFeature: 'Appears only under specific conditions (e.g. moon phase)',
    ),
  };
}